#!/usr/bin/env python

Import("env")
Import("env_modules")

env_godot_orchestrator = env_modules.Clone()
env_godot_orchestrator.Prepend(CPPEXTPATH=["./src"])
# Module files
env_godot_orchestrator.add_source_files(env.modules_sources, "./*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/api/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/common/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/orchestration/*.cpp")

env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/instances/*.cpp")

env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/constants/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/data/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/dialogue/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/flow_control/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/functions/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/input/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/math/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/memory/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/properties/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/resources/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/scene/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/signals/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/utilities/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/nodes/variables/*.cpp")

env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/serialization/*.cpp")
env_godot_orchestrator.add_source_files(env.modules_sources, "src/script/vm/*.cpp")

if env.editor_build:
    env_godot_orchestrator.add_source_files(env.modules_sources, "src/editor/*.cpp")
    env_godot_orchestrator.add_source_files(env.modules_sources, "src/editor/component_panels/*.cpp")
    
    env_godot_orchestrator.add_source_files(env.modules_sources, "src/editor/graph/*.cpp")
    env_godot_orchestrator.add_source_files(env.modules_sources, "src/editor/graph/actions/*.cpp")
    env_godot_orchestrator.add_source_files(env.modules_sources, "src/editor/graph/nodes/*.cpp")
    env_godot_orchestrator.add_source_files(env.modules_sources, "src/editor/graph/pins/*.cpp")
    
    env_godot_orchestrator.add_source_files(env.modules_sources, "src/editor/inspector/*.cpp")
    env_godot_orchestrator.add_source_files(env.modules_sources, "src/editor/plugins/*.cpp")
    env_godot_orchestrator.add_source_files(env.modules_sources, "src/editor/search/*.cpp")
    env_godot_orchestrator.add_source_files(env.modules_sources, "src/editor/theme/*.cpp")
