#!/usr/bin/env python

Import("env")
Import("env_modules")

env_game_help = env_modules.Clone()
# Module files
env_game_help.add_source_files(env.modules_sources, "*.cpp")
# env_game_help.add_source_files(env.modules_sources, "Terrain3D/src/*.cpp")
env_game_help.add_source_files(env.modules_sources, "foliage_manager/*.cpp")
env_game_help.add_source_files(env.modules_sources, "game_gui/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/animator/*.cpp")
env_game_help.add_source_files(env.modules_sources, "common/*.cpp")


env_game_help.add_source_files(env.modules_sources, "beehave/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/scene/*.cpp")

env_game_help.add_source_files(env.modules_sources, "logic/character_ai/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/character_ai/condition/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/character_ai/blackbord_item/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/character_shape/*.cpp")
env_game_help.add_source_files(env.modules_sources, "csv/*.cpp")
env_game_help.add_source_files(env.modules_sources, "unity/*.cpp")
env_game_help.add_source_files(env.modules_sources, "logic/navigation/*.cpp")
env_game_help.add_source_files(env.modules_sources, "blackboard/*.cpp")
env_game_help.add_source_files(env.modules_sources, "blackboard/bb_param/*.cpp")
# mterrain
env_game_help.add_source_files(env.modules_sources, "MTerrain/src/*.cpp")
env_game_help.add_source_files(env.modules_sources, "MTerrain/src/height_brushes/*.cpp")
env_game_help.add_source_files(env.modules_sources, "MTerrain/src/color_brushes/*.cpp")
env_game_help.add_source_files(env.modules_sources, "MTerrain/src/grass/*.cpp")
env_game_help.add_source_files(env.modules_sources, "MTerrain/src/navmesh/*.cpp")
env_game_help.add_source_files(env.modules_sources, "MTerrain/src/octmesh/*.cpp")
env_game_help.add_source_files(env.modules_sources, "MTerrain/src/path/*.cpp")
env_game_help.add_source_files(env.modules_sources, "MTerrain/src/hlod/*.cpp")
env_game_help.add_source_files(env.modules_sources, "MTerrain/src/editor/*.cpp")


env_game_help.add_source_files(env.modules_sources, "foliage_manager/*.cpp")

env_game_help.add_source_files(env.modules_sources, "PathMesh3D/extrude_profiles/*.cpp")
env_game_help.add_source_files(env.modules_sources, "PathMesh3D/gen/*.cpp")
env_game_help.add_source_files(env.modules_sources, "PathMesh3D/*.cpp")


if env.editor_build:
    env_game_help.add_source_files(env.modules_sources, "editor/*.cpp")
    env_game_help.add_source_files(env.modules_sources, "editor/resource_editor/*.cpp")
